version: '3'
services:
  mail-tool-api-php:
    container_name: mail-tool-api-php
    hostname: mail-tool-api-php
    restart: unless-stopped
    build:
      context: ./
    volumes:
      - .:/var/www/html
    networks:
      - mail-tool-api-network
    depends_on:
      - mail-tool-api-db
      - mail-tool-api-db-test

  mail-tool-api-nginx:
    image: nginx:1.23.3-alpine
    container_name: mail-tool-api-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "3080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - mail-tool-api-network
    depends_on:
      - mail-tool-api-php

  mail-tool-api-db:
    image: mariadb:10
    container_name: mail-tool-api-db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MARIADB_USER: mail
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: mail
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      - mail-tool-api-network
    hostname: mail-tool-api-db

  mail-tool-api-db-test:
    image: mariadb:10
    container_name: mail-tool-api-db-test
    restart: unless-stopped
    ports:
      - "4307:3306"
    networks:
      - mail-tool-api-network
    environment:
      MARIADB_USER: mail
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: mail
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    hostname: mail-tool-api-db-test



networks:
  mail-tool-api-network:
    driver: bridge
